### ISSUE TITLE
为什么0.0.111 npm包里 core 只有一个node-modules了?

### ISSUE THREAD

**Issue by whylost** [Serverless-Devs/core#18]
这是之前的包
![微信图片_20210629014927](https://user-images.githubusercontent.com/62528887/123681335-492a8600-d87c-11eb-9c1c-e63fe2f9c428.png)

这是现在的包
![1624902701(1)](https://user-images.githubusercontent.com/62528887/123681584-94dd2f80-d87c-11eb-9698-34f1d556f44b.jpg)

**Comment by whylost** [comment]
竟然没有入口文件.......

**Comment by xiezht** [comment]
执行 `s deploy` 后出现了以下错误。应该是同样的问题导致的。
![image](https://user-images.githubusercontent.com/18051618/123729575-c6c7b380-d8c7-11eb-96ea-e93d063cf599.png)

**Comment by anycodes** [comment]
已经在紧急处理。感谢各位的支持。稍等片刻。

**Comment by anycodes** [comment]
各位小伙伴，目前已经完成修复。

之前出问题的小伙伴可以考虑使用以下方法，清理一下缓存：`rm -rf ~/.s/component`

然后继续执行之前的命令即可。

问题复盘：由于意外发布一个版本，导致核心依赖包Core包出现了问题，产生了不必要的麻烦，最新的Core包版本为0.0.115，目前已经完成修复。

避免方案：之后我们会针对core包等核心组件，加入完整的ci/cd流程，保证发的包不会出现问题。

**Comment by anycodes** [comment]
> 执行 `s deploy` 后出现了以下错误。应该是同样的问题导致的。
> ![image](https://user-images.githubusercontent.com/18051618/123729575-c6c7b380-d8c7-11eb-96ea-e93d063cf599.png)

已经修复，请参考上面的方法，感谢支持，多谢理解。

**Comment by whylost** [comment]
问题已解决,提出的避免方案很有必要性. 感谢及时修复
