### ISSUE TITLE
s config 支持强制覆盖已有 credentials 参数

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs/core#27]

**Comment by xsahxl** [comment]
![image](https://user-images.githubusercontent.com/21330840/132471819-4a28c667-c326-45cd-a2e5-9ca0edf2e940.png)
指定什么参数好些？

**Comment by heimanba** [comment]
`-f`代表强制 替换掉 overwrite

s config add -f  --AccssKeyId i -a default
