### ISSUE TITLE
core 基于 daemon 进程更新机制建议

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs/core#28]
建议对该机制增加个强制等待更新的 flag，当设置了该 flag 后，daemon 进程的无阻塞更新就变为阻塞等待更新，更新后再执行后面的步骤。

不然开发者修了一个 bug，用户那边不能第一时间感知到，这个体验不太好。比如你发了个版本 1，这个版本修复了 bug，可以增加一个强制等待更新 flag，本地拿到这个 flag 后会直到更新到版本1 后再进行后续动作；如果发布了个版本 2，这个版本不是修复 bug 的，是优化，这样可以依赖 daemon 进行去更新 core 。 

当然上述场景应该也有其他解法，我是自己在使用时遇到这个问题了，所以先抛出来。

**Comment by heimanba** [comment]
现在又遇到更新时候造成的问题场景吗？是更新不及时还是?因为core的改造不会很大，请求强制更新的这个**flag**，其实会卡住主线程的，请求时机不太好把握

**Comment by git-qfzhang** [comment]
> 现在又遇到更新时候造成的问题场景吗？是更新不及时还是?因为core的改造不会很大，请求强制更新的这个**flag**，其实会卡住主线程的，请求时机不太好把握

遇到的问题就是之前让 huali 修复 core 的问题时，修复完成后，我这边在验证时，第一次验证是失败的，第二次验证才是成功的

**Comment by heimanba** [comment]
确实会遇到这个问题，主要在更新时候才会出现。而且主要是检测是否更新这个实际非常难把控，否则只能做在非deamon进程中，这样的话，又可能卡住主进程。。。所以暂时没有想到比较好的方式通知主进程更新
