### ISSUE TITLE
modifyProps方法为什么一定要传s.yaml路径呢？这个不应该是默认的吗

### ISSUE THREAD

**Issue by lowkeyrd** [Serverless-Devs/core#67]
modifyProps方法必须要传递s.yaml的路径，否则报错。我理解s.yaml应该在组件生命周期里自带的吗，为什么需要指定呢？如果需要指定路径，那直接用yaml.dump就可以了

https://github.com/Serverless-Devs/core/blob/master/src/common/modifyProps.ts#L8

**Comment by xsahxl** [comment]
core本身只提供方法，并不仅仅为s提供。modifyProps方法本身并不知道s.yaml的路径，后续vscode插件，应用中心等应该都会调用core的方法（脱离s）。

**Comment by xsahxl** [comment]
> modifyProps方法必须要传递s.yaml的路径，否则报错。我理解s.yaml应该在组件生命周期里自带的吗，为什么需要指定呢？如果需要指定路径，那直接用yaml.dump就可以了
> 
> https://github.com/Serverless-Devs/core/blob/master/src/common/modifyProps.ts#L8

core本身只提供方法，并不仅仅为s提供。modifyProps方法本身并不知道s.yaml的路径，后续vscode插件，应用中心等应该都会调用core的方法（脱离s）。
