### ISSUE TITLE
需要有一种默认更新组件的方法

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/core#69]
现在的组件每次都会自动更新，需要有一种机制无需自动更新组件，特别是在应用中心时候，我们可以将组件默认打入镜像，同时也不希望组件自动更新。

可以在s set中配置

```
sage: s set [commands] [options]

You can make some default settings for the tool here.

📖  Document: https://github.com/Serverless-Devs/Serverless-Devs/tree/master/docs/zh/command/set.md

Options:
  -h, --help  Display help for command

Commands:
  registry    👀  Set up a custom registry
  analysis    👉  Set to enable or disable analysis
  workspace   🙊  Set workspace path
  autoUpdate  Set enable or disable auto update component
```

**Comment by anycodes** [comment]
这个功能，我觉得可以讨论一下。自动更新这个事情，有好处也有坏处，要平衡一下。

如果提供一个不自动更新的模式，对用户的收益或者用户对他的诉求到底是多大。不太希望因为我们本身要做一些事情，修改我们的工具的行为。

至少目前，我还没有看到用户反馈，比较排斥目前的更新模式。

**Comment by heimanba** [comment]
确实暂时没有用户需求，主要是应用中心有需求



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Serverless-Devs/core] 需要有一种默认更新组件的方法 (Issue #69)




 
这个功能，我觉得可以讨论一下。自动更新这个事情，有好处也有坏处，要平衡一下。
 
如果提供一个不自动更新的模式，对用户的收益或者用户对他的诉求到底是多大。不太希望因为我们本身要做一些事情，修改我们的工具的行为。
 
至少目前，我还没有看到用户反馈，比较排斥目前的更新模式。
